[package]
name = "tba"
version = "0.0.0"
description = "A Rust wrapper for The Blue Alliance."
license = "ISC"
authors = ["Carl Colglazier <carl@carlcolglazier.com>"]

[lib]
name = "tba"
path = "src/lib.rs"
doc = true

[dependencies]
hyper = "0.3.11"
rustc-serialize = "0.3"
